{% set name = "bmadx" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bmad-sim/Bmad-X/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9f613b281d01f2cf1841e4b2a624fd599e575a2efbdac570c469aabaede9a395

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - bmad
    - distgen
    - matplotlib-base
    - numpy
    - openpmd-beamphysics
    - pytao
    - pytorch
    - pyyaml
    - scipy

test:
  imports:
    - bmadx

about:
  home: https://github.com/bmad-sim/bmadx
  summary:  Bmad particle tracking routines in Python using Pytorch
  description: |
    Bmad-X is a library-agnostic implementation of Bmad particle tracking routines in
    Python which allows for machine learning packages to be used in accelerator
    simulations. the underlying libraries are used for forward and backward
    mode automatic differentiation support enabling high-dimensional gradient-based
    optimization of beamlines, efficient hessian computation for gaussian process
    optimizers, model misalignment calibration, and phase-space reconstruction.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/bmad-sim/bmadx

extra:
  recipe-maintainers:
    - ken-lauer
